#!/bin/csh

if ( $8 == "") then
	echo "Usage: phyml.qsub path/input_dir list path/Gblocks_results path/PhyML_results begin end path/log_dir queue worker [aln_format]"
	exit(2)
endif

set current = $1
set taches  = $2
set gbresults = $3
set treeresults = $4
set log = $7

set begin = $5
set end = $6
set queue = $8
set worker = $9
set format = $10

echo $format

#if (! -d $current ) then
#echo "Directory $current is missing"
#exit(1)
#endif
#
#
#if (! -e $current/$taches ) then
#echo "File  $current/$taches is missing"
#exit(1)
#endif


if (! -d $gbresults) then
mkdir $gbresults
endif

if (! -d $treeresults) then
mkdir $treeresults
endif

if (! -d $log) then
mkdir $log
endif

set nber = 0

# nq = nb d'heures du job
set nq = 0

if ($queue == "q1hour") then
set nq = 1
endif

if ($queue == "q1day") then
set nq = 24
endif

if ($queue == "q1week") then
set nq = 168
endif

if ($nq  == 0 ) then 
	echo "Error: Queue $queue is not correct"
	@ nber = $nber + 1
endif

if ($nber > 0) then
	echo "EXIT"
	exit(1)
endif

echo "Queue $queue selected ($nq hours)"


set j = $begin
while ($j <= $end)

set job = "qsub -N phyml.$j -q $queue -o $log/phyml.$j.stdout -e $log/phyml.$j.stderr -l nodes=$worker"
echo $job
$job << EOF
\cp /pandata/lassalle/agrogenom/scripts/phyml_nogb.csh .
chmod u+x ./phyml_nogb.csh
echo "lance le script"
./phyml_nogb.csh $current $taches $gbresults $treeresults $nq $format
EOF
@ j = $j + 1
end
